#!/bin/bash

set -euo pipefail
#set -x

URL_BINS=https://cs.brown.edu/courses/csci1680/assets/ipstack-bins.tar.gz
URL_HASH=https://cs.brown.edu/courses/csci1680/assets/ipstack-bins.tar.gz.sha1sum.txt
CURL_ARGS="--retry 1 --retry-max-time 5 --fail"

RED='\033[0;31m'
LIGHTRED='\033[1;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
GRAY='\033[1;30m'
NC='\033[0m' # No Color


get_script_dir()
{
    local SOURCE_PATH="${BASH_SOURCE[0]}"
    local SYMLINK_DIR
    local SCRIPT_DIR
    # Resolve symlinks recursively
    while [ -L "$SOURCE_PATH" ]; do
        # Get symlink directory
        SYMLINK_DIR="$( cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd )"
        # Resolve symlink target (relative or absolute)
        SOURCE_PATH="$(readlink "$SOURCE_PATH")"
        # Check if candidate path is relative or absolute
        if [[ $SOURCE_PATH != /* ]]; then
            # Candidate path is relative, resolve to full path
            SOURCE_PATH=$SYMLINK_DIR/$SOURCE_PATH
        fi
    done
    # Get final script directory path from fully resolved source path
    SCRIPT_DIR="$(cd -P "$( dirname "$SOURCE_PATH" )" >/dev/null 2>&1 && pwd)"
    echo "$SCRIPT_DIR"
}


VERSION_FILE=$(get_script_dir)/bins_version.txt

verbose=0

display() {
    if [[ $verbose == 1 ]]; then
	echo $@
    fi
}

check_version() {
    rv=0
    latest_file=$(mktemp)
    curl -s --show-error --output $latest_file ${CURL_ARGS} ${URL_HASH} || rv=$?
    if [[ $rv != 0 ]]; then
	echo "Error fetching version hash:  curl returned ${rv}"
	return 2
    fi

    if [[ ! -e ${VERSION_FILE} ]]; then
	echo "No version file found, updating"
	needs_update=1
    else
	current=$(cat $VERSION_FILE)
	latest=$(cat $latest_file)
	if [[ "${current}" == "${latest}" ]]; then
	    needs_update=0
	else
	    needs_update=1
	fi
    fi
    return $needs_update
}

do_check() {
    rv=0
    check_version || rv=$?
    if [[ $rv == 1 ]]; then
	echo -e "${YELLOW}An update is available for your tester binaries, please run"
	echo -e "util/update_bins to update!${NC}"
    elif [[ $rv == 0 ]]; then
	echo "${GREEN}Binaries are already up to date.  Run util/update_bins --force to update anyway${NC}"
    else
	echo -e "${YELLOW}Error checking for updates.  Run 'util/update_bins --force' to update anyway${NC}"
    fi
    return $rv
}

do_update() {
    local script_dir
    local repo_root
    local target
    script_dir=$(get_script_dir)
    repo_root="$(realpath ${script_dir}/..)"

    target=/tmp/snowcast-bins.tar.gz
    curl --output $target ${CURL_ARGS} ${URL_BINS}
    tar -C ${repo_root} -zxvf $target
    rm -fv $target

    rv=0
    curl --output ${VERSION_FILE} ${CURL_ARGS} ${URL_HASH} || rv=$?
    if [[ $rv == 0 ]]; then
	echo -e "${GREEN}Updated to version $(cat ${VERSION_FILE})${NC}"
    fi
}

main() {
    needs_update=0
    check_only=0

    POSITIONAL=()
    while [[ $# -gt 0 ]]; do
	key=$1
	case $key in
	    --verbose|-v)
		shift
		verbose=1
		;;
	    --check-only)
		check_only=1
		shift
		;;
	    --force)
		shift
		needs_update=1
		;;
	    --help)
		shift
		do_help
		exit 0
		;;
	    *)
		POSITIONAL+=("$1")
		shift
	esac
    done
    set -- "${POSITIONAL[@]}"

    rv=0
    if [[ $check_only == 1 ]]; then
	do_check || rv=$?
	exit $rv
    fi

    if [[ $needs_update == 0 ]]; then
	rv=0
	check_version || rv=$?
	if [[ $rv == 1 ]]; then
	    needs_update=1
	elif [[ $rv == 0 ]]; then
	    echo -e "Binaries are already up to date.  Run 'util/update_bins --force' to update anyway"
	    exit 0
	else
	    echo -e "${RED}Error checking for updates.  Run 'util/update_bins --force' to update anyway${NC}"
	    exit 1
	fi
    fi

    if [[ $needs_update == 1 ]]; then
	do_update
    fi
}

main $@
